# -*- coding: utf-8 -*-

# self implementation generated from reading ui file 'AddCase.ui'
#
# Created by: PyQt5 UI code generator 5.15.10
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets

from Classes.Case import Case
from Classes.Officer import Officer


class AddCase(QtWidgets.QWidget):
    def __init__(self, parent=None):
        super().__init__(parent)
        self.setupUi()

    def setupUi(self):
        self.setObjectName("AddCase")
        self.resize(1007, 678)
        self.gridLayout_2 = QtWidgets.QGridLayout(self)
        self.gridLayout_2.setObjectName("gridLayout_2")
        self.gridLayout = QtWidgets.QGridLayout()
        self.gridLayout.setObjectName("gridLayout")
        spacerItem = QtWidgets.QSpacerItem(60, 20, QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Minimum)
        self.gridLayout.addItem(spacerItem, 6, 3, 1, 1)
        self.CaseStatusField = QtWidgets.QLineEdit(self)
        font = QtGui.QFont()
        font.setPointSize(15)
        self.CaseStatusField.setFont(font)
        self.CaseStatusField.setObjectName("CaseStatusField")
        self.gridLayout.addWidget(self.CaseStatusField, 9, 2, 1, 1)
        self.label_10 = QtWidgets.QLabel(self)
        font = QtGui.QFont()
        font.setPointSize(15)
        self.label_10.setFont(font)
        self.label_10.setAlignment(QtCore.Qt.AlignCenter)
        self.label_10.setObjectName("label_10")
        self.gridLayout.addWidget(self.label_10, 10, 0, 1, 1)
        spacerItem1 = QtWidgets.QSpacerItem(20, 40, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding)
        self.gridLayout.addItem(spacerItem1, 2, 2, 1, 1)
        self.label_9 = QtWidgets.QLabel(self)
        font = QtGui.QFont()
        font.setPointSize(15)
        self.label_9.setFont(font)
        self.label_9.setAlignment(QtCore.Qt.AlignCenter)
        self.label_9.setObjectName("label_9")
        self.gridLayout.addWidget(self.label_9, 9, 0, 1, 1)
        self.CaseIDField = QtWidgets.QLineEdit(self)
        font = QtGui.QFont()
        font.setPointSize(15)
        self.CaseIDField.setFont(font)
        self.CaseIDField.setObjectName("CaseIDField")
        self.gridLayout.addWidget(self.CaseIDField, 3, 2, 1, 1)
        self.label_2 = QtWidgets.QLabel(self)
        font = QtGui.QFont()
        font.setPointSize(15)
        self.label_2.setFont(font)
        self.label_2.setAlignment(QtCore.Qt.AlignCenter)
        self.label_2.setObjectName("label_2")
        self.gridLayout.addWidget(self.label_2, 3, 0, 1, 1)
        spacerItem2 = QtWidgets.QSpacerItem(20, 40, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding)
        self.gridLayout.addItem(spacerItem2, 11, 2, 1, 1)
        self.label_5 = QtWidgets.QLabel(self)
        font = QtGui.QFont()
        font.setPointSize(15)
        self.label_5.setFont(font)
        self.label_5.setAlignment(QtCore.Qt.AlignCenter)
        self.label_5.setObjectName("label_5")
        self.gridLayout.addWidget(self.label_5, 6, 0, 1, 1)
        self.CaseOfficerFkField = QtWidgets.QLineEdit(self)
        font = QtGui.QFont()
        font.setPointSize(15)
        self.CaseOfficerFkField.setFont(font)
        self.CaseOfficerFkField.setObjectName("CaseOfficerFkField")
        self.gridLayout.addWidget(self.CaseOfficerFkField, 10, 2, 1, 1)
        self.CaseEndField = QtWidgets.QDateEdit(self)
        font = QtGui.QFont()
        font.setPointSize(15)
        self.CaseEndField.setFont(font)
        self.CaseEndField.setObjectName("CaseEndField")
        self.gridLayout.addWidget(self.CaseEndField, 7, 2, 1, 1)
        self.label_3 = QtWidgets.QLabel(self)
        font = QtGui.QFont()
        font.setPointSize(15)
        self.label_3.setFont(font)
        self.label_3.setAlignment(QtCore.Qt.AlignCenter)
        self.label_3.setObjectName("label_3")
        self.gridLayout.addWidget(self.label_3, 8, 0, 1, 1)
        spacerItem3 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Minimum)
        self.gridLayout.addItem(spacerItem3, 6, 1, 1, 1)
        self.label_6 = QtWidgets.QLabel(self)
        font = QtGui.QFont()
        font.setPointSize(15)
        self.label_6.setFont(font)
        self.label_6.setAlignment(QtCore.Qt.AlignCenter)
        self.label_6.setObjectName("label_6")
        self.gridLayout.addWidget(self.label_6, 7, 0, 1, 1)
        self.BackBtn = QtWidgets.QPushButton(self)
        font = QtGui.QFont()
        font.setPointSize(15)
        self.BackBtn.setFont(font)
        self.BackBtn.setObjectName("BackBtn")
        self.gridLayout.addWidget(self.BackBtn, 12, 0, 1, 1)
        self.label = QtWidgets.QLabel(self)
        font = QtGui.QFont()
        font.setPointSize(25)
        self.label.setFont(font)
        self.label.setObjectName("label")
        self.gridLayout.addWidget(self.label, 1, 2, 1, 1)
        self.AddCaseDataBtn = QtWidgets.QPushButton(self)
        font = QtGui.QFont()
        font.setPointSize(15)
        self.AddCaseDataBtn.setFont(font)
        self.AddCaseDataBtn.setObjectName("AddCaseDataBtn")
        self.gridLayout.addWidget(self.AddCaseDataBtn, 12, 2, 1, 1)
        self.CaseStartField = QtWidgets.QDateEdit(self)
        font = QtGui.QFont()
        font.setPointSize(15)
        self.CaseStartField.setFont(font)
        self.CaseStartField.setObjectName("CaseStartField")
        self.gridLayout.addWidget(self.CaseStartField, 6, 2, 1, 1)
        self.CaseDescriptionField = QtWidgets.QTextEdit(self)
        font = QtGui.QFont()
        font.setPointSize(15)
        self.CaseDescriptionField.setFont(font)
        self.CaseDescriptionField.setObjectName("CaseDescriptionField")
        self.gridLayout.addWidget(self.CaseDescriptionField, 8, 2, 1, 1)
        self.gridLayout_2.addLayout(self.gridLayout, 1, 1, 3, 3)
        spacerItem4 = QtWidgets.QSpacerItem(20, 40, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding)
        self.gridLayout_2.addItem(spacerItem4, 0, 1, 1, 1)
        spacerItem5 = QtWidgets.QSpacerItem(200, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.gridLayout_2.addItem(spacerItem5, 1, 4, 1, 1)
        spacerItem6 = QtWidgets.QSpacerItem(200, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.gridLayout_2.addItem(spacerItem6, 1, 0, 1, 1)
        spacerItem7 = QtWidgets.QSpacerItem(20, 40, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding)
        self.gridLayout_2.addItem(spacerItem7, 4, 1, 1, 1)

        self.AddCaseDataBtn.clicked.connect(self.add_case)

        self.retranslateUi()

    def retranslateUi(self):
        _translate = QtCore.QCoreApplication.translate
        self.setWindowTitle(_translate("self", "self"))
        self.label_10.setText(_translate("self", "Officer ID"))
        self.label_9.setText(_translate("self", "Status"))
        self.label_2.setText(_translate("self", "Case ID"))
        self.label_5.setText(_translate("self", "Start Date"))
        self.label_3.setText(_translate("self", "Description"))
        self.label_6.setText(_translate("self", "End Date"))
        self.BackBtn.setText(_translate("self", "Back"))
        self.label.setText(_translate("self", "Add Case"))
        self.AddCaseDataBtn.setText(_translate("self", "Add"))

    def add_case(self):
        case_id = self.CaseIDField.text()
        start_date = self.CaseStartField.text()
        end_date = self.CaseEndField.text()
        description = self.CaseDescriptionField.toPlainText()
        status = self.CaseStatusField.text()
        officer_fk = self.CaseOfficerFkField.text()
        
        if case_id == "" or start_date == "" or end_date == "" or description == "" or status == "" or officer_fk == "":
            msg = QtWidgets.QMessageBox()
            msg.setText("Please fill all fields")
            msg.setIcon(QtWidgets.QMessageBox.Information)
            msg.setText("All Data must be filled")
            msg.setWindowTitle("Error")
            msg.exec_()
            return
        tmp = Case.get_all()
        tmp = [x[0] for x in tmp]

        tmpOfficer = Officer.get_all()
        tmpOfficer = [x[0] for x in tmpOfficer]

        try:
            case_id = int(case_id)
        except:
            msg = QtWidgets.QMessageBox()
            msg.setIcon(QtWidgets.QMessageBox.Information)
            msg.setText("Case ID must be an integer")
            msg.setWindowTitle("Error")
            msg.exec_()
            return
        try:
            officer_fk = int(officer_fk)
        except:
            msg = QtWidgets.QMessageBox()
            msg.setIcon(QtWidgets.QMessageBox.Information)
            msg.setText("Officer ID must be an integer")
            msg.setWindowTitle("Error")
            msg.exec_()
            return
        if case_id in tmp:
            msg = QtWidgets.QMessageBox()
            msg.setIcon(QtWidgets.QMessageBox.Information)
            msg.setText("Case ID already exists")
            msg.setWindowTitle("Error")
            msg.exec_()
            return
        if officer_fk not in tmpOfficer:
            msg = QtWidgets.QMessageBox()
            msg.setIcon(QtWidgets.QMessageBox.Information)
            msg.setText("Officer ID does not exist")
            msg.setWindowTitle("Error")
            msg.exec_()
            return
        case = Case(case_id, start_date, end_date, description, status, officer_fk)
        case.insert_into_database()
        msg = QtWidgets.QMessageBox()
        msg.setIcon(QtWidgets.QMessageBox.Information)
        msg.setText("Case added successfully")
        msg.setWindowTitle("Success")
        msg.exec_()
        self.CaseIDField.clear()
        self.CaseStartField.clear()
        self.CaseEndField.clear()
        self.CaseDescriptionField.clear()
        self.CaseStatusField.clear()
        self.CaseOfficerFkField.clear()




# if __name__ == "__main__":
#     import sys
#     app = QtWidgets.QApplication(sys.argv)
#     self = QtWidgets.QWidget()
#     ui = Ui_self()
#     ui.setupUi(self)
#     self.show()
#     sys.exit(app.exec_())
