# -*- coding: utf-8 -*-

# self implementation generated from reading ui file 'Cases.ui'
#
# Created by: PyQt5 UI code generator 5.15.10
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


import os
import sys
from PyQt5 import QtCore, QtGui, QtWidgets
from Classes.Case import Case 

curr_dir = os.path.dirname('systemdb\Classes\Case.py')
parent_dir = os.path.dirname(curr_dir)
sys.path.insert(0, parent_dir)


class Cases(QtWidgets.QWidget):
    def __init__(self, parent=None):
        super().__init__(parent)
        self.setupUi()
        self.Cases = Case.get_all()
        self.populate_table()

    def setupUi(self):
        self.setObjectName("Cases")
        self.resize(1007, 678)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.sizePolicy().hasHeightForWidth())
        self.setSizePolicy(sizePolicy)
        self.gridLayout_2 = QtWidgets.QGridLayout(self)
        self.gridLayout_2.setObjectName("gridLayout_2")
        spacerItem = QtWidgets.QSpacerItem(20, 40, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Fixed)
        self.gridLayout_2.addItem(spacerItem, 0, 1, 1, 1)
        self.gridLayout = QtWidgets.QGridLayout()
        self.gridLayout.setObjectName("gridLayout")
        self.horizontalLayout_2 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_2.setObjectName("horizontalLayout_2")
        spacerItem1 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_2.addItem(spacerItem1)
        self.CaseSearchField = QtWidgets.QLineEdit(self)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.MinimumExpanding, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.CaseSearchField.sizePolicy().hasHeightForWidth())
        self.CaseSearchField.setSizePolicy(sizePolicy)
        font = QtGui.QFont()
        font.setPointSize(15)
        self.CaseSearchField.setFont(font)
        self.CaseSearchField.setObjectName("CaseSearchField")
        self.horizontalLayout_2.addWidget(self.CaseSearchField)
        self.CaseSearchBtn = QtWidgets.QPushButton(self)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.CaseSearchBtn.sizePolicy().hasHeightForWidth())
        self.CaseSearchBtn.setSizePolicy(sizePolicy)
        font = QtGui.QFont()
        font.setPointSize(15)
        self.CaseSearchBtn.setFont(font)
        self.CaseSearchBtn.setObjectName("CaseSearchBtn")
        self.horizontalLayout_2.addWidget(self.CaseSearchBtn)
        spacerItem2 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_2.addItem(spacerItem2)
        self.gridLayout.addLayout(self.horizontalLayout_2, 1, 0, 1, 1)
        self.CaseScrollArea = QtWidgets.QScrollArea(self)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.MinimumExpanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.CaseScrollArea.sizePolicy().hasHeightForWidth())
        self.CaseScrollArea.setSizePolicy(sizePolicy)
        self.CaseScrollArea.setWidgetResizable(True)
        self.CaseScrollArea.setObjectName("CaseScrollArea")
        self.scrollAreaWidgetContents = QtWidgets.QWidget()
        self.scrollAreaWidgetContents.setGeometry(QtCore.QRect(0, 0, 893, 515))
        self.scrollAreaWidgetContents.setObjectName("scrollAreaWidgetContents")
        self.CaseScrollArea.setWidget(self.scrollAreaWidgetContents)
        self.gridLayout.addWidget(self.CaseScrollArea, 2, 0, 1, 1)
        self.horizontalLayout = QtWidgets.QHBoxLayout()
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.label = QtWidgets.QLabel(self)
        font = QtGui.QFont()
        font.setPointSize(20)
        self.label.setFont(font)
        self.label.setAlignment(QtCore.Qt.AlignCenter)
        self.label.setObjectName("label")
        self.horizontalLayout.addWidget(self.label)
        self.AddCaseBtn = QtWidgets.QPushButton(self)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.AddCaseBtn.sizePolicy().hasHeightForWidth())
        self.AddCaseBtn.setSizePolicy(sizePolicy)
        font = QtGui.QFont()
        font.setPointSize(15)
        self.AddCaseBtn.setFont(font)
        self.AddCaseBtn.setObjectName("AddCaseBtn")
        self.horizontalLayout.addWidget(self.AddCaseBtn)
        self.BackBtn = QtWidgets.QPushButton(self)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.BackBtn.sizePolicy().hasHeightForWidth())
        self.BackBtn.setSizePolicy(sizePolicy)
        font = QtGui.QFont()
        font.setPointSize(15)
        self.BackBtn.setFont(font)
        self.BackBtn.setObjectName("BackBtn")
        self.horizontalLayout.addWidget(self.BackBtn)
        self.gridLayout.addLayout(self.horizontalLayout, 0, 0, 1, 1)
        self.gridLayout_2.addLayout(self.gridLayout, 1, 1, 1, 1)
        spacerItem3 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Minimum)
        self.gridLayout_2.addItem(spacerItem3, 1, 0, 1, 1)
        spacerItem4 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Minimum)
        self.gridLayout_2.addItem(spacerItem4, 1, 2, 1, 1)

        self.retranslateUi()
        
        self.CasesTable = QtWidgets.QTableWidget(self)
        self.CasesTable.setObjectName("CasesTable")
        self.CasesTable.setColumnCount(7) # Number of columns
        self.CasesTable.setHorizontalHeaderLabels(['CaseID', 'Start Date', 'End Date', 'Description',
                                                      'Status','OfficerID','Remove'])
        self.gridLayout.addWidget(self.CasesTable, 2, 0, 1, 1)
        self.CaseSearchBtn.clicked.connect(self.search_Cases)

    def retranslateUi(self):
        _translate = QtCore.QCoreApplication.translate
        self.setWindowTitle(_translate("self", "self"))
        self.CaseSearchBtn.setText(_translate("self", "Search"))
        self.label.setText(_translate("self", "Cases"))
        self.AddCaseBtn.setText(_translate("self", "Add"))
        self.BackBtn.setText(_translate("self", "Back"))
        
    def populate_table(self):
        self.CasesTable.setRowCount(len(self.Cases))
        for i, Case in enumerate(self.Cases):
            for j, data in enumerate(Case):
                item = QtWidgets.QTableWidgetItem(str(data))
                self.CasesTable.setItem(i, j, item)
            remove_button = QtWidgets.QPushButton("Remove")
            remove_button.clicked.connect(lambda _, Case=Case: self.remove_Case(Case))
            self.CasesTable.setCellWidget(i, 6, remove_button)
        self.CasesTable.resizeColumnsToContents()
        
    def search_Cases(self):
        search_value = self.CaseSearchField.text()
        self.CaseSearchField.clear() 
        if search_value:
            try:
                search_value = int(search_value)
            except:
                QtWidgets.QMessageBox.warning(self, "Search", "Please enter a valid CaseID")
                return
            self.Cases = Case.search(search_value)
            if not self.Cases:
                msg = QtWidgets.QMessageBox()
                msg.setIcon(QtWidgets.QMessageBox.Information)
                msg.setText("No Cases found")
                msg.setWindowTitle("Search")
                msg.exec_()
            else:
                self.populate_table()
        else:
            self.Cases = Case.get_all()
            self.populate_table()
            
    def remove_Case(self, case):
        Case.delete("CaseID",case[0])
        self.Cases = Case.get_all()
        self.populate_table()
        
        


# if __name__ == "__main__":
#     import sys
#     app = QtWidgets.QApplication(sys.argv)
#     self = QtWidgets.QWidget()
#     ui = Ui_self()
#     ui.setupUi(self)
#     self.show()
#     sys.exit(app.exec_())
