# -*- coding: utf-8 -*-

# self implementation generated from reading ui file 'Victims.ui'
#
# Created by: PyQt5 UI code generator 5.15.10
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.

import sys
import os
from PyQt5 import QtCore, QtGui, QtWidgets
curr_dir = os.path.dirname('systemdb\Classes\Victim.py')
parent_dir = os.path.dirname(curr_dir)
sys.path.insert(0, parent_dir)
from Classes.Victim import Victim
from Classes.VictimPhoneNumber import VictimPhoneNumber
from Classes.Injuries import Injuries
from Classes.Affects import Affects

class Victims(QtWidgets.QWidget):
    def __init__(self, parent=None):
        super().__init__(parent)
        self.setupUi()
        self.victims =  Victim.get_all()
        self.populate_table()

    def setupUi(self):
        self.setObjectName("Victims")
        self.resize(1007, 678)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.sizePolicy().hasHeightForWidth())
        self.setSizePolicy(sizePolicy)
        self.gridLayout_2 = QtWidgets.QGridLayout(self)
        self.gridLayout_2.setObjectName("gridLayout_2")
        spacerItem = QtWidgets.QSpacerItem(20, 40, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Fixed)
        self.gridLayout_2.addItem(spacerItem, 0, 1, 1, 1)
        self.gridLayout = QtWidgets.QGridLayout()
        self.gridLayout.setObjectName("gridLayout")
        self.horizontalLayout_2 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_2.setObjectName("horizontalLayout_2")
        spacerItem1 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_2.addItem(spacerItem1)
        self.VictimSearchField = QtWidgets.QLineEdit(self)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.MinimumExpanding, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.VictimSearchField.sizePolicy().hasHeightForWidth())
        self.VictimSearchField.setSizePolicy(sizePolicy)
        font = QtGui.QFont()
        font.setPointSize(15)
        self.VictimSearchField.setFont(font)
        self.VictimSearchField.setObjectName("VictimSearchField")
        
        self.horizontalLayout_2.addWidget(self.VictimSearchField)
        self.VictimSearchBtn = QtWidgets.QPushButton(self)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.VictimSearchBtn.sizePolicy().hasHeightForWidth())
        self.VictimSearchBtn.setSizePolicy(sizePolicy)
        self.VictimSearchBtn.clicked.connect(self.search_victims)
        font = QtGui.QFont()
        font.setPointSize(15)
        self.VictimSearchBtn.setFont(font)
        self.VictimSearchBtn.setObjectName("VictimSearchBtn")
        self.horizontalLayout_2.addWidget(self.VictimSearchBtn)
        spacerItem2 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_2.addItem(spacerItem2)
        self.gridLayout.addLayout(self.horizontalLayout_2, 1, 0, 1, 1)
        self.VictimScrollArea = QtWidgets.QScrollArea(self)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.MinimumExpanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.VictimScrollArea.sizePolicy().hasHeightForWidth())
        self.VictimScrollArea.setSizePolicy(sizePolicy)
        self.VictimScrollArea.setWidgetResizable(True)
        self.VictimScrollArea.setObjectName("VictimScrollArea")
        self.scrollAreaWidgetContents = QtWidgets.QWidget()
        self.scrollAreaWidgetContents.setGeometry(QtCore.QRect(0, 0, 893, 515))
        self.scrollAreaWidgetContents.setObjectName("scrollAreaWidgetContents")
        self.VictimScrollArea.setWidget(self.scrollAreaWidgetContents)
        self.gridLayout.addWidget(self.VictimScrollArea, 2, 0, 1, 1)

        self.VictimTable = QtWidgets.QTableWidget(self)
        self.VictimTable.setObjectName("VictimTable")
        self.VictimTable.setColumnCount(8) # Number of columns
        self.VictimTable.setHorizontalHeaderLabels(['VictimID', 'First Name', 'Last Name', 'Date of Birht', 'Age', 'Gender', 'Address','Remove'])
        self.gridLayout.addWidget(self.VictimTable, 2, 0, 1, 1)

        self.horizontalLayout = QtWidgets.QHBoxLayout()
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.label = QtWidgets.QLabel(self)
        font = QtGui.QFont()
        font.setPointSize(20)
        self.label.setFont(font)
        self.label.setAlignment(QtCore.Qt.AlignCenter)
        self.label.setObjectName("label")
        self.horizontalLayout.addWidget(self.label)
        self.AddVictimBtn = QtWidgets.QPushButton(self)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.AddVictimBtn.sizePolicy().hasHeightForWidth())
        self.AddVictimBtn.setSizePolicy(sizePolicy)
        font = QtGui.QFont()
        font.setPointSize(15)
        self.AddVictimBtn.setFont(font)
        self.AddVictimBtn.setObjectName("AddVictimBtn")
        self.horizontalLayout.addWidget(self.AddVictimBtn)
        self.BackBtn = QtWidgets.QPushButton(self)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.BackBtn.sizePolicy().hasHeightForWidth())
        self.BackBtn.setSizePolicy(sizePolicy)
        font = QtGui.QFont()
        font.setPointSize(15)
        self.BackBtn.setFont(font)
        self.BackBtn.setObjectName("BackBtn")
        self.horizontalLayout.addWidget(self.BackBtn)
        self.gridLayout.addLayout(self.horizontalLayout, 0, 0, 1, 1)
        self.gridLayout_2.addLayout(self.gridLayout, 1, 1, 1, 1)
        spacerItem3 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Minimum)
        self.gridLayout_2.addItem(spacerItem3, 1, 0, 1, 1)
        spacerItem4 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Minimum)
        self.gridLayout_2.addItem(spacerItem4, 1, 2, 1, 1)

        self.retranslateUi()

    def retranslateUi(self):
        _translate = QtCore.QCoreApplication.translate
        self.setWindowTitle(_translate("self", "self"))
        self.VictimSearchBtn.setText(_translate("self", "Search"))
        self.label.setText(_translate("self", "Victims"))
        self.AddVictimBtn.setText(_translate("self", "Add"))
        self.BackBtn.setText(_translate("self", "Back"))

    def populate_table(self):
        self.VictimTable.setRowCount(len(self.victims))
        for i, victim in enumerate(self.victims):
            for j, data in enumerate(victim):
                item = QtWidgets.QTableWidgetItem(str(data))
                self.VictimTable.setItem(i, j, item)
            remove_btn = QtWidgets.QPushButton("Remove")
            remove_btn.clicked.connect(lambda _, victim=victim: self.remove_victim(victim))
            self.VictimTable.setCellWidget(i, 7, remove_btn)

    def search_victims(self):
        search_value = self.VictimSearchField.text()
        self.VictimSearchField.clear() 
        if search_value:
            self.victims = Victim.search(search_value)
            if not self.victims:
                msg = QtWidgets.QMessageBox()
                msg.setIcon(QtWidgets.QMessageBox.Information)
                msg.setText("No suspects found")
                msg.setWindowTitle("Search")
                msg.exec_()
            else:
                self.populate_table()
        else:
            self.victims = Victim.get_all()
            self.populate_table()
    def remove_victim(self, victim):
        Affects.delete('VictimID', victim[0])
        Injuries.delete('Victim_ID', victim[0])
        VictimPhoneNumber.delete('Victim_ID', victim[0])    
        Victim.delete('VictimID', victim[0])
        self.victims = Victim.get_all()
        self.populate_table()

# if __name__ == "__main__":
#     import sys
#     app = QtWidgets.QApplication(sys.argv)
#     self = QtWidgets.QWidget()
#     ui = Ui_self()
#     ui.setupUi(self)
#     self.show()
#     sys.exit(app.exec_())
